= Avisos legais
:allow-uri-read: 


<<<<<<< CABEÇALHO --- permalink: legal-notices.html barra lateral: barra lateral palavras-chave: resumo: ---



= Avisos legais

[role="lead"]
Avisos legais fornecem acesso a declarações de direitos autorais, marcas registradas, patentes e muito mais.



== Direitos autorais

link:https://www.netapp.com/company/legal/copyright/["https://www.netapp.com/company/legal/copyright/"^]



== Marcas Registradas

NETAPP, o logotipo da NETAPP e as marcas listadas na página de Marcas Registradas da NetApp são marcas registradas da NetApp, Inc. Outros nomes de empresas e produtos podem ser marcas registradas de seus respectivos proprietários.

link:https://www.netapp.com/company/legal/trademarks/["https://www.netapp.com/company/legal/trademarks/"^]



== Patentes

Uma lista atual de patentes de propriedade da NetApp pode ser encontrada em:

link:https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf["https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf"^]



== Política de Privacidade

link:https://www.netapp.com/company/legal/privacy-policy/["https://www.netapp.com/company/legal/privacy-policy/"^]



== Código aberto

Os arquivos de aviso fornecem informações sobre direitos autorais e licenças de terceiros usados no software NetApp .

* https://docs.netapp.com/us-en/bluexp-setup-admin/media/notice.pdf["Aviso para o NetApp Console"^]


[]
====
'''
permalink: legal-notices.html sidebar: sidebar keywords: # sem palavras-chave summary: # sem resumo --- = Avisos legais :icons: font :imagesdir: ./media/

[role="lead"]
Avisos legais fornecem acesso a declarações de direitos autorais, marcas registradas, patentes e muito mais.

== Direitos autorais

link:https://www.netapp.com/company/legal/copyright/["https://www.netapp.com/company/legal/copyright/"^]

== Marcas Registradas

NETAPP, o logotipo da NETAPP e as marcas listadas na página de Marcas Registradas da NetApp são marcas registradas da NetApp, Inc. Outros nomes de empresas e produtos podem ser marcas registradas de seus respectivos proprietários.

link:https://www.netapp.com/company/legal/trademarks/["https://www.netapp.com/company/legal/trademarks/"^]

== Patentes

Uma lista atual de patentes de propriedade da NetApp pode ser encontrada em:

link:https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf["https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf"^]

== Política de privacidade

link:https://www.netapp.com/company/legal/privacy-policy/["https://www.netapp.com/company/legal/privacy-policy/"^]

== Código aberto

Os arquivos de aviso fornecem informações sobre direitos autorais e licenças de terceiros usados no software NetApp .

>>>>>>> db096cfa4bc2bcbc1a7a0fefc9249c9cbef4831b

====