---
settings:
  name: NetApp Ransomware Resilience
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  release_notes_autogen:
    release_notes_repo: console-relnotes
  rss_page: whats-new.html
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentação sobre NetApp Ransomware Resilience
    url: "/index.html"
  - title: Notas de lançamento
    entries:
    - title: Novidades em Resiliência contra Ransomware
      url: "/whats-new.html"
    - title: Limitações conhecidas
      url: "/rp-reference-limitations.html"
  - title: Começar
    entries:
    - title: Saiba mais sobre resiliência ao ransomware
      url: "/concept-ransomware-resilience.html"
    - title: Pré-requisitos
      url: "/rp-start-prerequisites.html"
    - title: Início rápido
      url: "/rp-start-quick-start.html"
    - title: Configurar resiliência contra ransomware
      url: "/rp-start-setup.html"
    - title: Configurar licenciamento
      url: "/rp-start-licenses.html"
    - title: Descubra cargas de trabalho
      url: "/rp-start-discover.html"
  - title: Use a resiliência do ransomware
    entries:
    - title: Resiliência do Access Ransomware
      url: "/rp-start-login.html"
    - title: Ver o estado da carga de trabalho
      url: "/rp-use-dashboard.html"
    - title: Proteger e detectar
      entries:
      - title: Revisar proteção
        url: "/task-review-protection.html"
      - title: Configurar destinos de backup
        url: "/task-backup-destination.html"
      - title: Proteja as cargas de trabalho
        url: "/rp-use-protect.html"
      - title: Configurar detecção de atividade do usuário
        entries:
        - title: Saiba mais sobre detecção de atividade do usuário
          url: "/concept-user-behavior.html"
        - title: Requisitos de detecção de atividade do usuário
          url: "/reference-user-activity-requirements.html"
        - title: Configurar agentes e coletores
          url: "/suspicious-user-activity.html"
      - title: Gerenciar grupos de proteção
        url: "/task-protection-group.html"
      - title: Escaneie dados de identificação pessoal
        url: "/task-classify.html"
    - title: Responder e recuperar
      entries:
      - title: Responder a um alerta detectado
        url: "/rp-use-alert.html"
      - title: Recuperar-se de um ataque de ransomware
        url: "/rp-use-recover.html"
    - title: Realize um exercício de prontidão
      url: "/rp-start-simulate.html"
    - title: Configurar SIEM
      url: "/task-siem.html"
    - title: Baixar relatórios
      url: "/rp-use-reports.html"
  - section: support
  - title: Perguntas frequentes
    url: "/rp-start-faq.html"
  - title: Avisos legais
    url: "/legal-notices.html"
product-family:
  name: NetApp Data Services
  repo: data-services-family
