---
sidebar: sidebar 
permalink: rp-reference-limitations.html 
keywords: ransomware protection, protect against ransomware attacks, anti-ransomware, role-based access control, rbac, role, permission, access rights, organization,project,account 
summary: Limitações conhecidas identificam plataformas, dispositivos ou funções que não são suportados por esta versão do produto. 
---
= Limitações conhecidas na NetApp Ransomware Resilience
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Limitações conhecidas identificam plataformas, dispositivos ou funções que não são suportados por esta versão do produto ou que não interoperam corretamente com ele. Revise essas limitações cuidadosamente.



== Problema com a opção de reinicialização do exercício de prontidão

Se você selecionar um volume ONTAP 9.11.1 para o exercício de prontidão para ataque de ransomware, o Ransomware Resilience enviará um alerta.  Se você recuperar os dados usando a opção "clone-to-volume" e redefinir o drill, a operação de redefinição falhará.



== Limitações do Amazon FSx for NetApp ONTAP

As seguintes limitações se aplicam ao Amazon FSx para ONTAP:

* As políticas de backup não são compatíveis com Amazon FSx for ONTAP. Nesse ambiente, você deve executar operações de backup usando o Amazon FSx for backups. Você pode restaurar essas cargas de trabalho usando Ransomware Resilience.
* As operações de restauração são executadas somente a partir de instantâneos.




== Limitações do Azure NetApp Files

As seguintes limitações se aplicam ao Azure NetApp Files:

* Estratégias de proteção contra ransomware com políticas de backup não são compatíveis com o Azure NetApp Files. Em vez disso, você pode usar Azure NetApp Files backup.
* Estratégias de proteção contra ransomware com replicação não são suportadas para Azure NetApp Files.
* Azure NetApp Files não oferece suporte a FPolicy nem à atividade de comportamento do usuário. Azure NetApp Files também não oferece suporte à análise forense de entropia.
* Ao selecionar uma estratégia de proteção, certifique-se de que sua programação de snapshots seja compatível com o Azure NetApp Files. A programação de snapshots mais frequente disponível no Azure NetApp Files é a cada hora.
* Não é recomendável usar link:reference-soar.html["Playbooks SOAR"] com Azure NetApp Files devido às APIs do Azure NetApp Files bloquearem ações automatizadas.
* Alguns dados de eventos não estão incluídos em link:task-siem.html["Relatórios SIEM"] para configurações do Azure NetApp Files.




== Limitações do Google Cloud NetApp Volumes

As seguintes limitações se aplicam ao Google Cloud NetApp Volumes:

* Atualmente, você só pode aplicar estratégias de proteção baseadas em criptografia e FPolicy às cargas de trabalho do Google Cloud NetApp Volumes. Não é possível aplicar estratégias de proteção baseadas no comportamento do usuário.
* Estratégias de proteção com replicação não são suportadas atualmente para Google Cloud NetApp Volumes

