---
sidebar: sidebar 
permalink: rp-start-prerequisites.html 
keywords: bluexp ransomware protection, ransomware protection prerequisites, resilience 
summary: Comece a usar o NetApp Ransomware Resilience verificando o suporte ao seu ambiente, acesso à rede, login e navegador da web. 
---
= Pré-requisitos de NetApp Ransomware Resilience
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/get-started/


[role="lead"]
Comece a usar o NetApp Ransomware Resilience verificando se seu ambiente operacional, acesso à rede e navegador da web estão prontos.

Para usar o Ransomware Resilience, certifique-se de atender aos pré-requisitos.



== Sistemas suportados

Certifique-se de estar usando um sistema compatível:

* NAS ONTAP local (usando protocolos NFS e CIFS) com ONTAP versão 9.11.1 e superior
* SAN ONTAP local (usando protocolos FC, iSCSI e NVMe) com ONTAP versão 9.17.1 e superior
* Cloud Volumes ONTAP 9.11.1 ou superior para AWS (usando protocolos NFS e CIFS)
* Cloud Volumes ONTAP 9.11.1 ou superior para Google Cloud Platform (usando protocolos NFS e CIFS)
* Cloud Volumes ONTAP 9.12.1 ou superior para Microsoft Azure (usando protocolos NFS e CIFS)
* Cloud Volumes ONTAP 9.17.1 ou superior para AWS, Google Cloud Platform e Microsoft Azure (usando protocolos FC, iSCSI e NVMe)
* Amazon FSx for NetApp ONTAP, que usa proteção autônoma contra ransomware (ARP e não ARP/AI)



NOTE: Para usar ARP/AI no ONTAP, é necessário ter o ONTAP 9.16 ou superior.  + O ONTAP não oferece suporte à proteção contra ransomware para volumes FlexGroup , volumes de ponto de montagem, volumes de caminho de montagem, volumes offline e volumes de proteção de dados (DP).  Certifique-se de revisarlink:https://docs.netapp.com/us-en/ontap/anti-ransomware/use-cases-restrictions-concept.html["Configurações suportadas e não suportadas no ONTAP"^] .



== Requisitos do NetApp Console

A configuração do seu NetApp Console requer:

* Uma conta de usuário do NetApp Console com privilégios de administrador da organização para descobrir recursos.
* Uma organização e sistema de console com pelo menos um agente de console ativo conectado a umlink:concept-ransomware-resilience.html#supported-backup-targets-systems-and-workload-data-sources["sistema suportado"] .
+
** Se seus clusters ONTAP locais ou Cloud Volumes ONTAP na AWS ou na nuvem Azure não estiverem configurados no Console, consultelink:https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html["Aprenda a configurar um agente de console"^] elink:https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["requisitos padrão do console"^] .
+

NOTE: Se você tiver vários agentes do Console em uma única organização do Console, o Ransomware Resilience verificará os recursos do ONTAP em todos os agentes do Console além daquele que está selecionado no momento na IU do Console.



* O agente do Console deve ter o `cloudmanager-ransomware-protection` contêiner em estado ativo.
* Pelo menos um sistema de console com um cluster ONTAP local da NetApp ou Cloud Volumes ONTAP na AWS ou Azure.  O Ransomware Resilience oferece suporte aos protocolos NAS (NFS e SMB) e SAN (iSCSI, FC e NVMe).
+
** O Ransomware Resilience é compatível com clusters ONTAP ou Cloud Volumes ONTAP com ONTAP versão 9.11.1 ou superior.
+

NOTE: Para usar a Resiliência a Ransomware em cargas de trabalho SAN, você precisa estar executando o ONTAP 9.17.1 ou posterior.







== Requisitos do ONTAP

* Você precisa estar executando o ONTAP 9.11.1 ou posterior com uma licença ONTAP One habilitada na instância ONTAP local.  Para obter mais informações sobre o suporte do ONTAP , consultelink:https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["Visão geral da proteção autônoma contra ransomware"^] .
* Para aplicar configurações de proteção (como ativar a Proteção Autônoma contra Ransomware), o Ransomware Resilience precisa de permissões de administrador no cluster ONTAP . O cluster ONTAP deveria ter sido integrado usando apenas credenciais de usuário administrador do cluster ONTAP .



NOTE: Se você conectou um cluster ONTAP ao Console com credenciais não administrativas, [você deve atualizar as credenciais no cluster ONTAP ](#update-non-admin-user-permissions-in-an-ontap-system).



== Backups de dados

* Uma conta no NetApp StorageGRID, AWS S3, Azure Blob ou Google Cloud Platform para destinos de backup com as permissões de acesso apropriadas configuradas.
+
Consulte o https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["Lista de permissões AWS, Azure ou S3"^] para mais detalhes.

* O NetApp Backup and Recovery não precisa ser habilitado no sistema.
+
O Ransomware Resilience ajuda a configurar um destino de backup por meio da opção Configurações. Ver link:rp-use-settings.html["Configurar definições"] .





== Comportamento suspeito do usuário

Para que o Ransomware Resilience forneça alertas sobre comportamento suspeito do usuário, você deve configurar um agente de atividade do usuário. Para mais informações, consulte link:suspicious-user-activity.html["Configurar a detecção de atividades suspeitas de usuários no NetApp Ransomware Resilience"].



== Atualizar permissões de usuários não administradores em um sistema ONTAP

Se você precisar atualizar as permissões de usuários não administradores para um sistema específico, siga estas etapas.

. Efetue login no Console e procure o sistema que precisa ter suas permissões de usuário ONTAP atualizadas.
. Selecione o sistema para ver detalhes.
. Selecione *Exibir informações adicionais* para exibir o nome de usuário.
. Faça login na CLI do cluster ONTAP como usuário administrador.
. Exibe as funções existentes para esse usuário. Digitar:
+
[listing]
----
security login show -user-or-group-name <username>
----
. Alterar a função do usuário. Digitar:
+
[listing]
----
security login modify -user-or-group-name <username> -application console|http|ontapi|ssh|telnet -authentication-method password -role admin
----
. Retorne ao NetApp Console para usar a Resiliência a Ransomware.

