---
sidebar: sidebar 
permalink: rp-start-faq.html 
keywords: ransomware protection faq, ransomware protection frequently asked questions 
summary: Encontre uma resposta para uma pergunta frequente sobre a NetApp Ransomware Resilience. 
---
= Perguntas frequentes sobre NetApp Ransomware Resilience
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Estas perguntas frequentes podem ajudar se você estiver apenas procurando uma resposta rápida para uma pergunta sobre o NetApp Ransomware Resilience.



== Implantação

.Você precisa de uma licença para usar o Ransomware Resilience?
Você pode usar os seguintes tipos de licença:

* Inscreva-se para um teste gratuito de 30 dias.
* Adquira uma assinatura pré-paga (PAYGO) do NetApp Intelligent Services e Ransomware Resilience com o Amazon Web Services (AWS) Marketplace, o Google Cloud Marketplace e o Microsoft Azure Marketplace.
* Traga sua própria licença (BYOL), que é um arquivo de licença NetApp (NLF) que você obtém com seu representante de vendas da NetApp . Você pode usar o número de série da licença para ativar o BYOL na seção Licenses and subscriptions do console.


.Como habilitar a resiliência a ransomware?
Você pode acessar o Ransomware Resilience no NetApp Console. Certifique-se de que você tem link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-roles.html["funções de acesso"] e link:rp-start-prerequisites.html["pré-requisitos"]. Se você configurou com sucesso um agente de console, poderá então... link:rp-start-discover.html["descobrir cargas de trabalho"].

Para mais informações, consultelink:rp-start-login.html["Resiliência do Access Ransomware"] elink:rp-start-quick-start.html["Guia de início rápido para resiliência a ransomware"] .

.A Resiliência a Ransomware está disponível nos modos padrão, restrito e privado?
A Resiliência a Ransomware está disponível atualmente apenas no modo padrão.

Para obter uma explicação sobre esses modos em todos os serviços de dados da NetApp , consulte https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modos de implantação do NetApp Console"^] .

.Como funciona a cobrança do Ransomware Resilience?
Você pode experimentar o Ransomware Resilience com um teste gratuito de 30 dias. A NetApp não cobra pelo uso da versão de teste do Ransomware Resilience.

Se você tiver o Backup and Recovery e o Ransomware Resilience, quaisquer dados comuns protegidos por ambos os produtos serão cobrados somente pelo Ransomware Resilience.

Quando uma carga de trabalho é classificada como protegida, ela é contabilizada na capacidade contratada ou na assinatura PAYGO. Ransomware Resilience classifica uma carga de trabalho como protegida quando uma política de detecção está habilitada com pelo menos uma política de snapshot ou de backup. Cargas de trabalho descobertas com uma política de detecção, mas _sem_ nenhuma política de backup ou snapshot, são classificadas como em risco. Cargas de trabalho em risco não são contabilizadas na capacidade contratada.

As cargas de trabalho protegidas são contabilizadas na capacidade adquirida ou na assinatura após o término do período de avaliação gratuita. Ransomware Resilience é cobrada por GB para os dados associados às cargas de trabalho protegidas (conforme relatado pelo ONTAP) antes das eficiências.

Ao considerar o dimensionamento, os custos de licenciamento são baseados na capacidade lógica do sistema de arquivos ativo (ou seja, o espaço consumido pelos snapshots não está incluído).



== Acesso

.Qual é a URL de Resiliência a Ransomware?
Em um navegador, digite https://console.netapp.com/["https://console.netapp.com/ransomware-resilience"^] Para acessar o Console.

.Como são gerenciadas as permissões de acesso?
https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Saiba mais sobre as funções de acesso do Console para todos os serviços"^]. A resiliência a ransomware também possui link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-ransomware-roles.html["funções de acesso dedicadas"^].

.Qual a melhor resolução para o dispositivo?
A resolução de dispositivo recomendada para o Ransomware Resilience é 1920x1080 ou melhor.

.Qual navegador devo usar?
Você pode acessar o NetApp Console com qualquer navegador web moderno.



== Interoperabilidade

.O Ransomware Resilience está ciente das configurações de proteção no ONTAP?
Sim, o Ransomware Resilience descobre agendamentos de snapshots definidos no ONTAP.

.Como a resiliência a ransomware interage com NetApp Backup and Recovery?
Ransomware Resilience funciona com NetApp Backup and Recovery para descobrir e definir políticas de snapshot e backup para cargas de trabalho de compartilhamento de arquivos. Ransomware Resilience também funciona com NetApp Backup and Recovery para realizar a recuperação consistente de arquivos e cargas de trabalho.

Para licenciamento e faturamento, o Ransomware Resilience pode ser integrado ao Backup e Recuperação, mesmo que você não tenha uma licença separada para Backup e Recuperação. Se você tiver o Backup and Recovery e o Ransomware Resilience, quaisquer dados comuns protegidos por ambos os produtos serão cobrados somente pelo Ransomware Resilience.



== Cargas de trabalho

.O que é uma carga de trabalho no contexto da resiliência a ransomware?
Uma carga de trabalho é uma máquina virtual ou um compartilhamento de arquivos.

.Como o Ransomware Resilience prioriza os dados de carga de trabalho?
A prioridade da carga de trabalho (crítica, padrão, importante) é determinada pelas frequências de snapshots já aplicadas a cada volume associado à carga de trabalho e pelos backups agendados.

link:rp-use-protect.html["Aprenda sobre a prioridade ou importância da carga de trabalho"] .

.Quais cargas de trabalho o Ransomware Resilience suporta?
A ferramenta de Resiliência a Ransomware pode identificar as seguintes cargas de trabalho: Oracle, compartilhamentos de arquivos, armazenamento em blocos, máquinas virtuais e datastores de máquinas virtuais.

.Como associar dados a uma carga de trabalho?
A Resiliência a Ransomware descobre os volumes e as extensões de arquivo e os associa à carga de trabalho apropriada.

.O que é uma carga de trabalho protegida?
Na Resiliência a Ransomware, uma carga de trabalho exibe o status *protegida* quando possui uma política de _detecção_ primária ativada, o que significa que... link:concept-ransomware-resilience.html["Proteção Autônoma contra Ransomware (ARP)"] Está habilitado em todos os volumes relacionados à carga de trabalho.

.O que é uma carga de trabalho "de risco"?
Se uma carga de trabalho não tiver uma política de detecção primária ativada, ela será rotulada como "em risco", mesmo que tenha uma política de backup e snapshot ativada. Para proteção contra ransomware, você deve habilitar um link:rp-use-protect.html#add-a-ransomware-protection-strategy["política de detecção"].

.Adicionei um novo volume, mas ele ainda não apareceu. O que devo fazer?
Se você adicionou um novo volume ao seu ambiente, inicie a descoberta da carga de trabalho novamente. Após o volume ter sido descoberto, link:rp-use-protect.html#add-a-ransomware-protection-strategy["Aplicar políticas de proteção para proteger o novo volume."].



== Políticas de proteção

.As políticas de resiliência a ransomware coexistem com outros tipos de políticas de carga de trabalho?
No momento, o Backup e Recuperação (Cloud Backup) oferece suporte a uma política de backup por volume. Se você configurar a proteção de backup com Backup e Recuperação, ela compartilhará as políticas de backup com a Resiliência a Ransomware.

As cópias de instantâneos não são limitadas e podem ser adicionadas separadamente de cada serviço.

.Quais políticas são necessárias em uma estratégia de proteção contra ransomware?
UM link:rp-use-protect.html#add-a-ransomware-protection-strategy["estratégia de proteção contra ransomware"] Requer:

* uma política de detecção de ransomware, e
* uma política instantânea


Uma política de backup não é necessária na estratégia de resiliência ao ransomware.

.O Ransomware Resilience está ciente das configurações de proteção no ONTAP?
Sim, o Ransomware Resilience detecta os agendamentos de snapshots definidos no ONTAP. Ele também detecta se o ARP e o FPolicy estão habilitados em todos os volumes de uma carga de trabalho detectada. As informações exibidas no painel do Ransomware Resilience são agregadas de outras NetApp soluções e produtos.

.A Resiliência a Ransomware está ciente das políticas já criadas em NetApp Backup and Recovery?
Sim, se você tiver cargas de trabalho gerenciadas em Backup and Recovery, as políticas gerenciadas por esses produtos serão integradas ao Ransomware Resilience.

.É possível modificar as políticas herdadas do NetApp Backup and Recovery?
Não, você não pode modificar as políticas gerenciadas pelo NetApp Backup and Recovery a partir do Ransomware Resilience. Você gerencia quaisquer alterações nessas políticas no NetApp Backup and Recovery.

.Se existirem políticas do ONTAP (como ARP, FPolicy e snapshots), essas políticas são alteradas no Ransomware Resilience?
Não. O Ransomware Resilience não modifica nenhuma política de detecção existente (configurações ARP, FPolicy) do ONTAP.

.O que acontece se você adicionar novas políticas em Backup and Recovery depois de se inscrever no Ransomware Resilience?
A Resiliência contra Ransomware reconhece políticas recém-criadas e alterações de políticas em NetApp Backup and Recovery.

.É possível alterar as políticas a partir do ONTAP?
Sim, você pode alterar as políticas do ONTAP no Ransomware Resilience.  Você também pode criar novas políticas no Ransomware Resilience e aplicá-las às cargas de trabalho.  Esta ação substitui as políticas ONTAP existentes pelas políticas criadas no Ransomware Resilience.

.É possível desativar políticas no ONTAP?
É possível desativar o ARP nas políticas de detecção usando a interface do usuário do System Manager, as APIs ou a CLI no ONTAP.

Você pode desabilitar o FPolicy e as políticas de backup aplicando uma política diferente que não as inclua.
