---
sidebar: sidebar 
permalink: rp-start-setup.html 
keywords: bluexp, ransomware protection, aws, azure 
summary: Para usar o Ransomware Resilience, siga algumas etapas para configurá-lo. 
---
= Configurar a NetApp Ransomware Resilience
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Configure o NetApp Ransomware Resilience preparando um destino de backup, revisando os pré-requisitos e configurando o NetApp Console e o agente do Console.



[[prepare-the-backup-destination]]
== Preparar o destino do backup

Prepare um dos seguintes destinos de backup:

* NetApp StorageGRID
* Serviços Web da Amazon
* Plataforma Google Cloud
* Microsoft Azure


Depois de configurar as opções no próprio destino de backup, você o configurará posteriormente como um destino de backup no Ransomware Resilience. Para obter detalhes sobre como configurar o destino de backup no Ransomware Resilience, consulte link:task-backup-destination.html["Configurar destinos de backup"].



[[prepare-storagegrid-to-become-a-backup-destination]]
=== Preparar o StorageGRID para se tornar um destino de backup

Se você quiser usar o StorageGRID como seu destino de backup, consulte https://docs.netapp.com/us-en/storagegrid-117/index.html["Documentação do StorageGRID"^] para obter detalhes sobre StorageGRID.



[[prepare-aws-to-become-a-backup-destination]]
=== Prepare a AWS para se tornar um destino de backup

* Crie uma conta na AWS.
* Configurar https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["Permissões da AWS"^] na AWS.


Para obter detalhes sobre como gerenciar seu armazenamento do AWS no Console, consulte https://docs.netapp.com/us-en/console-setup-admin/task-viewing-amazon-s3.html["Gerencie seus buckets do Amazon S3"^] .



[[prepare-azure-to-become-a-backup-destination]]
=== Prepare o Azure para se tornar um destino de backup

* Crie uma conta no Azure.
* Configurar https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["Permissões do Azure"^] no Azure.


Para obter detalhes sobre como gerenciar seu armazenamento do Azure no Console, consulte https://docs.netapp.com/us-en/storage-management-blob-storage/task-view-azure-blob-storage.html["Gerencie suas contas de armazenamento do Azure"^] .



[[set-up-the-netapp-console]]
== Configurar o NetApp Console

O próximo passo é configurar o NetApp Console e o NetApp Ransomware Resilience.

Análise https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Requisitos do console para o modo padrão"^] .



[[create-a-console-agent]]
=== Criar um agente de console

Contate seu representante de vendas da NetApp para experimentar ou usar este serviço. Em seguida, o agente do Console inclui os recursos necessários para o NetApp Ransomware Resilience.

Para criar um agente do Console para Resiliência a Ransomware, entre em contato com o administrador da sua organização do Console que tem permissão para criar agentes do Console e consulte  https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["como criar um agente de console"^].


NOTE: Se você tiver vários agentes do Console, o Ransomware Resilience verifica os dados em todos os agentes do Console, não apenas naquele que está sendo exibido no Console. O serviço verifica os dados em todos os projetos e agentes do Console associados à organização.
