---
sidebar: sidebar 
permalink: rp-start-faq.html 
keywords: ransomware protection faq, ransomware protection frequently asked questions 
summary: Encontre uma resposta para uma pergunta frequente sobre a resiliência do NetApp Ransomware. 
---
= Perguntas frequentes sobre a resiliência do NetApp Ransomware
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Estas perguntas frequentes podem ajudar se você estiver apenas procurando uma resposta rápida para uma pergunta sobre a resiliência do NetApp Ransomware.



== Implantação

*Você precisa de uma licença para usar o Ransomware Resilience?*

Você pode usar os seguintes tipos de licença:

* Inscreva-se para um teste gratuito de 30 dias.
* Adquira uma assinatura pré-paga (PAYGO) do NetApp Intelligent Services e Ransomware Resilience com o Amazon Web Services (AWS) Marketplace, o Google Cloud Marketplace e o Microsoft Azure Marketplace.
* Traga sua própria licença (BYOL), que é um arquivo de licença NetApp (NLF) que você obtém do seu representante de vendas NetApp . Você pode usar o número de série da licença para ativar o BYOL na seção Licenças e assinaturas do Console.


*Como você habilita a Resiliência contra Ransomware?*  O Ransomware Resilience não requer nenhuma ativação.  Você pode acessar o Ransomware Resilience no NetApp Console.

Para começar, você precisa se inscrever ou entrar em contato com seu representante de vendas da NetApp para experimentar este serviço.  Então, quando você usar o agente do Console, ele incluirá os recursos apropriados para Resiliência de Ransomware.

Para começar a usar o Ransomware Resilience, selecione "Começar a descobrir cargas de trabalho" na página inicial.

*O Ransomware Resilience está disponível nos modos padrão, restrito e privado?*  No momento, o Ransomware Resilience está disponível apenas no modo padrão. Fique ligado para mais informações.

Para obter uma explicação sobre esses modos em todos os serviços de dados da NetApp , consulte https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Modos de implantação do NetApp Console"^] .



== Acesso

*Qual é o URL de resiliência do Ransomware?*  Em um navegador, digite https://console.netapp.com/["https://console.netapp.com/ransomware-resilience"^] para acessar o Console.

*Como as permissões de acesso são gerenciadas?* https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Saiba mais sobre as funções de acesso do Console para todos os serviços"^] .

*Qual é a melhor resolução do dispositivo?* A resolução de dispositivo recomendada para o Ransomware Resilience é 1920x1080 ou melhor.

*Qual navegador devo usar?* Qualquer navegador moderno.



== Interação com outros serviços

*O Ransomware Resilience está ciente das configurações de proteção feitas no NetApp ONTAP?*  Sim, o Ransomware Resilience descobre agendamentos de snapshots definidos no ONTAP.

*Se você definir uma política usando o Ransomware Resilience, precisará fazer alterações futuras apenas neste serviço?*  Recomendamos que você faça alterações na política de Resiliência contra Ransomware.

*Como o Ransomware Resilience interage com o NetApp Backup and Recovery e o SnapCenter?*

A Ransomware Resilience usa os seguintes produtos e serviços:

* Backup e recuperação para descobrir e definir políticas de backup e instantâneos para cargas de trabalho de compartilhamento de arquivos
* SnapCenter ou SnapCenter para VMware para descobrir e definir políticas de snapshot e backup para cargas de trabalho de aplicativos e VMs.


Além disso, o Ransomware Resilience usa o Backup and Recovery e o SnapCenter / SnapCenter for VMware para executar uma recuperação consistente de arquivos e cargas de trabalho.



== Cargas de trabalho

*O que compõe uma carga de trabalho?* Uma carga de trabalho é um aplicativo, uma VM ou um compartilhamento de arquivos. Uma carga de trabalho inclui todos os volumes usados por uma única instância do aplicativo.  Por exemplo, uma instância do Oracle DB implantada em ora3.host.com pode ter vol1 e vol2 para seus dados e logs, respectivamente.  Esses volumes juntos constituem a carga de trabalho para aquela instância específica da instância do Oracle DB.

*Como o Ransomware Resilience prioriza os dados da carga de trabalho?*  A prioridade dos dados é determinada pelas cópias instantâneas feitas e pelos backups agendados.

A prioridade da carga de trabalho (crítica, padrão, importante) é determinada pelas frequências de snapshot já aplicadas a cada volume associado à carga de trabalho.

link:rp-use-protect.html["Aprenda sobre a prioridade ou importância da carga de trabalho"] .

*Quais cargas de trabalho o Ransomware Resilience suporta?*

O Ransomware Resilience pode identificar as seguintes cargas de trabalho: Oracle, MySQL, compartilhamentos de arquivos, armazenamento em bloco, VMs e datastores de VM.

Além disso, se você estiver usando o SnapCenter ou o SnapCenter for VMware, todas as cargas de trabalho suportadas por esses produtos também serão identificadas no Ransomware Resilience, e o Ransomware Resilience poderá protegê-las e recuperá-las de maneira consistente com a carga de trabalho.

*Como você associa dados a uma carga de trabalho?*

A resiliência do ransomware associa dados a uma carga de trabalho das seguintes maneiras:

* O Ransomware Resilience descobre os volumes e as extensões de arquivo e os associa à carga de trabalho apropriada.
* Além disso, se você tiver o SnapCenter ou o SnapCenter for VMware e tiver configurado cargas de trabalho no Backup and Recovery, o Ransomware Resilience descobrirá as cargas de trabalho gerenciadas pelo SnapCenter e SnapCenter for VMware e seus volumes associados.


*O que é uma carga de trabalho "protegida"?* No Ransomware Resilience, uma carga de trabalho mostra um status "protegida" quando tem uma política de detecção primária ativada.  Por enquanto, isso significa que o ARP está habilitado em todos os volumes relacionados à carga de trabalho.

*O que é uma carga de trabalho "em risco"?* Se uma carga de trabalho não tiver uma política de detecção primária habilitada, ela estará "em risco", mesmo que tenha uma política de backup e snapshot habilitada.

*Novo volume adicionado, mas ainda não aparece* Se você adicionou um novo volume ao seu ambiente, inicie a descoberta novamente e aplique políticas de proteção para proteger esse novo volume.



== Políticas de proteção

*As políticas de ransomware Ransomware Resilience coexistem com outros tipos de políticas de carga de trabalho?*  No momento, o Backup e Recuperação (Cloud Backup) oferece suporte a uma política de backup por volume.  Portanto, Backup and Recovery e Ransomware Resilience compartilham políticas de backup.

As cópias de instantâneos não são limitadas e podem ser adicionadas separadamente de cada serviço.

*Quais políticas são necessárias em uma estratégia de proteção contra ransomware?*

As seguintes políticas são necessárias na estratégia de proteção contra ransomware:

* Política de detecção de ransomware
* Política de instantâneo


Uma política de backup não é necessária na estratégia de resiliência ao ransomware.

*O Ransomware Resilience está ciente das configurações de proteção feitas no NetApp ONTAP?*

Sim, o Ransomware Resilience descobre agendamentos de snapshots definidos no ONTAP e se ARP e FPolicy estão habilitados em todos os volumes em uma carga de trabalho descoberta. As informações que você vê inicialmente no Painel são agregadas de outras soluções e produtos da NetApp .

*A Ransomware Resilience está ciente das políticas já feitas no Backup and Recovery e no SnapCenter?*

Sim, se você tiver cargas de trabalho gerenciadas no Backup and Recovery ou no SnapCenter, as políticas gerenciadas por esses produtos serão trazidas para o Ransomware Resilience.

*Você pode modificar políticas transferidas do NetApp Backup and Recovery e/ou SnapCenter?*

Não, você não pode modificar políticas gerenciadas pelo Backup and Recovery ou SnapCenter do Ransomware Resilience.  Você gerencia quaisquer alterações nessas políticas no Backup and Recovery ou no SnapCenter.

*Se existirem políticas do ONTAP (já habilitadas no Gerenciador do Sistema, como ARP, FPolicy e snapshots), elas serão alteradas no Ransomware Resilience?*

Não. O Ransomware Resilience não modifica nenhuma política de detecção existente (configurações ARP, FPolicy) do ONTAP.

*O que acontece se você adicionar novas políticas no Backup and Recovery ou no SnapCenter após se inscrever no Ransomware Resilience?*

O Ransomware Resilience reconhece quaisquer novas políticas criadas no Backup and Recovery ou no SnapCenter.

*Você pode alterar as políticas do ONTAP?*

Sim, você pode alterar as políticas do ONTAP no Ransomware Resilience.  Você também pode criar novas políticas no Ransomware Resilience e aplicá-las às cargas de trabalho.  Esta ação substitui as políticas ONTAP existentes pelas políticas criadas no Ransomware Resilience.

*É possível desabilitar políticas?*

Você pode desabilitar o ARP nas políticas de detecção usando a interface do usuário, as APIs ou a CLI do System Manager.

Você pode desabilitar o FPolicy e as políticas de backup aplicando uma política diferente que não as inclua.
