---
sidebar: sidebar 
permalink: task-users-manage.html 
keywords: user activity detection, 
summary: Após criar o conector de diretório de usuários no NetApp Ransomware Resilience, você pode bloquear e desbloquear usuários e excluí-los dos alertas. Você também pode excluir caminhos de arquivos da geração de alertas. 
---
= Gerencie alertas e usuários bloqueados no NetApp Ransomware Resilience
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Após configurar o monitoramento do comportamento do usuário no NetApp Ransomware Resilience, você pode personalizar alertas e gerenciar usuários bloqueados. Personalizar os alertas permite que você exclua usuários ou caminhos de arquivos específicos da geração de um alerta. Bloquear usuários serve para responder a eventos de ransomware e impedir atividades maliciosas de usuários.

Você precisa ter link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/suspicious-user-activity.html#create-a-user-activity-agent["configurou um agente de atividade do usuário, habilitou uma política com detecção de atividade do usuário e criou um conector de diretório de usuários"] para bloquear usuários.


TIP: Você pode link:task-automate-user-activity.html["automatizar respostas"] aos eventos de detecção de atividade do usuário.



[[manage-blocked-users]]
== Gerenciar usuários bloqueados

Você pode bloquear usuários quando acreditar que eles são responsáveis por atividades maliciosas.

.Bloquear usuários
. Em Resiliência a Ransomware, selecione **Configurações**.
. No painel de Configurações, localize o bloco Monitoramento de atividade do usuário e selecione **Gerenciar**.
. Selecione a guia **Usuários**.
. Selecione **Bloquear usuários**.
. Selecione a duração do bloqueio: pode ser de uma hora até 24 horas ou permanente.
. Selecione a caixa de seleção ao lado dos nomes dos usuários que você deseja bloquear.
. Selecione **Block**.


.Modificar a lista de usuários bloqueados
. Em Resiliência a Ransomware, selecione **Configurações**.
. No painel de Configurações, localize o bloco Monitoramento de atividade do usuário e selecione **Gerenciar**.
. Selecione a guia **Usuários**.
. Selecione **Editar bloqueio de usuário**.
. Escolha a modificação. Para modificar a duração do bloqueio, selecione **Período para usuários bloqueados** e modifique a duração. Para remover usuários da lista de usuários bloqueados, selecione **Desbloquear usuários**.
. Selecione a caixa de seleção ao lado do nome do usuário bloqueado cujo status você deseja alterar.
. Selecione **Salvar**.




[[exclude-users-from-alerts]]
== Excluir usuários dos alertas

Se houver determinados usuários confiáveis cujo comportamento possa acionar alertas de comportamento do usuário, você pode excluí-los dos alertas.

.Excluir usuários dos alertas
. Em Resiliência a Ransomware, selecione **Configurações**.
. No painel de Configurações, localize o bloco Monitoramento de atividade do usuário e selecione **Gerenciar**.
. Selecione a guia **Excluído do monitoramento**.
. Para visualizar usuários individuais na interface do usuário, escolha **Selecionar manualmente**. Para carregar uma lista de usuários excluídos, selecione **Carregar**.
+
.. Se você selecionou **Select manually**, marque a caixa de seleção ao lado dos nomes dos usuários específicos que deseja excluir.
.. Se você selecionar **Carregar**, faça o download do arquivo CSV ou JSON que inclui a lista de todos os usuários. Selecione **Baixar** para acessar a lista.
+
Em sua máquina local, revise o arquivo. Remova os nomes de todos os usuários para os quais você deseja manter a detecção. Quando a lista incluir apenas os nomes dos usuários que você deseja excluir da detecção, salve-a.

+
Em NetApp Ransomware Resilience, selecione **Carregar**. Localize e carregue o arquivo.



. Selecione **Adicionar** para concluir a inclusão dos usuários na lista de exclusão.
. Na aba **Excluídos do monitoramento**, os nomes dos usuários removidos dos alertas de detecção de comportamento do usuário agora são exibidos no painel.



TIP: Você também pode excluir um usuário diretamente de um alerta. Para mais informações, consulte link:rp-use-alert.html["Responder a alertas de ransomware"].

.Remover usuários da lista de usuários excluídos
. No painel de Configurações, localize o cartão Atividade do usuário e selecione **Manage**.
. Selecione a guia **Excluído do monitoramento**.
. Selecione **Adicionar**.
. Para excluir usuários individuais da interface do usuário, escolha **Select manually**.
. Localize o nome do usuário que deseja remover da seleção de usuários excluídos. Selecione o menu de ações (`...`) na linha com o nome do usuário e então **Remover**.
. Na caixa de diálogo, selecione **Remove** para confirmar que deseja remover os usuários selecionados.




[[exclude-file-paths-from-monitoring]]
== Excluir caminhos de arquivos do monitoramento

Cada caminho de arquivo deve começar com o nome de um volume. Ele pode incluir até três subdiretórios para esse volume, por exemplo "volume/diretório/subdiretório/subdiretório2". Você pode excluir caminhos de arquivo inserindo-os manualmente ou carregando um arquivo CSV que liste os caminhos.

.Passos
. Em Resiliência a Ransomware, selecione **Configurações**.
. No bloco de monitoramento de atividades do usuário, selecione **Gerenciar**.
. Selecione a guia *Excluído do monitoramento*.
. Selecione **Adicionar** para inserir os caminhos dos arquivos a serem excluídos.
. Para inserir os caminhos dos arquivos na interface do usuário, selecione a opção *Inserir manualmente* e digite o caminho do arquivo, por exemplo "volume/diretório/subdiretório/". Para inserir caminhos de arquivos adicionais, selecione **Selecionar caminho do arquivo**.
. Para carregar uma lista de caminhos de arquivos, selecione o botão de opção **Carregar**. Selecione o botão de upload para escolher o arquivo CSV.
. Selecione **Adicionar**.


.Resultado
Quando a operação for concluída com sucesso, NetApp Ransomware Resilience começará a excluir os arquivos nos caminhos selecionados do monitoramento de comportamento suspeito do usuário. Você pode revisar a lista de caminhos a qualquer momento no menu Configurações. Se você precisar ativar novamente o monitoramento para os caminhos de arquivo, basta removê-los da lista.



[[next-steps]]
== Próximos passos

* link:task-automate-user-activity.html["Automatize respostas a eventos de detecção de atividade do usuário"]

