= Avaliação de risco de segurança do Digital Advisor
:allow-uri-read: 




[[security-risk-assessment-from-digital-advisor]]
=== Avaliação de risco de segurança do Digital Advisor

O BlueXP ransomware protection agora coleta informações sobre riscos de segurança de cluster altos e críticos do NetApp Digital Advisor. Se um risco for encontrado, o BlueXP ransomware protection exibirá esta recomendação no painel *Ações recomendadas* do Dashboard: "corrigir uma vulnerabilidade de segurança conhecida no cluster <name>." Na recomendação do Dashboard, selecione *Revisar e corrigir* para revisar o Digital Advisor e o artigo de Common Vulnerability & Exposure (CVE) relacionado. Se houver vários riscos de segurança, revise os detalhes no Digital Advisor.

Consulte https://docs.netapp.com/us-en/active-iq/index.html["Documentação do Digital Advisor"^] .



[[back-up-to-google-cloud-platform]]
=== Fazer backup no Google Cloud Platform

Com esta versão, você pode definir um destino de backup para um bucket do Google Cloud Platform.  Anteriormente, você só podia adicionar destinos de backup ao NetApp StorageGRID, Amazon Web Services e Microsoft Azure.

https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-backup-destination.html["Saiba mais sobre como configurar as configurações de BlueXP ransomware protection"].



[[support-for-google-cloud-platform]]
=== Suporte para Google Cloud Platform

O serviço agora oferece suporte ao Cloud Volumes ONTAP para Google Cloud Platform para proteção de armazenamento.  Anteriormente, o serviço suportava apenas o Cloud Volumes ONTAP para Amazon Web Services e Microsoft Azure, além de NAS local.

https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html["Saiba mais sobre a BlueXP ransomware protection e fontes de dados suportadas, destinos de backup e ambientes de trabalho"] .



[[role-based-access-control]]
=== Controle de acesso baseado em função

Agora você pode limitar o acesso a atividades específicas com o controle de acesso baseado em função (RBAC).  A BlueXP ransomware protection usa duas funções do BlueXP: Administrador de conta do BlueXP e Administrador sem conta (Visualizador).

Para obter detalhes sobre as ações que cada função pode executar, consulte https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-roles.html["Privilégios de controle de acesso baseados em funções"] .
