= Avaliação de risco de segurança do Digital Advisor
:allow-uri-read: 




=== Avaliação de risco de segurança do Digital Advisor

A BlueXP ransomware protection agora coleta informações sobre riscos de segurança altos e críticos relacionados a um cluster do NetApp Digital Advisor.  Se algum risco for encontrado, a BlueXP ransomware protection fornece uma recomendação no painel *Ações recomendadas* do Painel: "Corrigir uma vulnerabilidade de segurança conhecida no cluster <nome>".  Na recomendação no Painel, clicar em *Revisar e corrigir* sugere revisar o Digital Advisor e um artigo sobre Vulnerabilidade e Exposição Comuns (CVE) para resolver o risco de segurança.  Se houver vários riscos de segurança, revise as informações no Digital Advisor.

Consulte https://docs.netapp.com/us-en/active-iq/index.html["Documentação do Digital Advisor"^] .



=== Fazer backup no Google Cloud Platform

Com esta versão, você pode definir um destino de backup para um bucket do Google Cloud Platform.  Anteriormente, você só podia adicionar destinos de backup ao NetApp StorageGRID, Amazon Web Services e Microsoft Azure.

https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-settings.html["Saiba mais sobre como configurar as configurações de BlueXP ransomware protection"] .



=== Suporte para Google Cloud Platform

O serviço agora oferece suporte ao Cloud Volumes ONTAP para Google Cloud Platform para proteção de armazenamento.  Anteriormente, o serviço suportava apenas o Cloud Volumes ONTAP para Amazon Web Services e Microsoft Azure, além de NAS local.

https://docs.netapp.com/us-en/bluexp-ransomware-protection/concept-ransomware-protection.html["Saiba mais sobre a BlueXP ransomware protection e fontes de dados suportadas, destinos de backup e ambientes de trabalho"] .



=== Controle de acesso baseado em função

Agora você pode limitar o acesso a atividades específicas com o controle de acesso baseado em função (RBAC).  A BlueXP ransomware protection usa duas funções do BlueXP: Administrador de conta do BlueXP e Administrador sem conta (Visualizador).

Para obter detalhes sobre as ações que cada função pode executar, consulte https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-roles.html["Privilégios de controle de acesso baseados em funções"] .
