= Habilitar classificação de dados e busca de informações de identificação pessoal (PII)
:allow-uri-read: 




=== Habilitar classificação de dados e busca de informações de identificação pessoal (PII)

Com esta versão, você pode habilitar a BlueXP classification, um componente principal da família BlueXP , para escanear e classificar dados em suas cargas de trabalho de compartilhamento de arquivos.  Classificar dados ajuda você a identificar se seus dados incluem informações pessoais ou privadas, o que pode aumentar os riscos de segurança.  Esse processo também afeta a importância da carga de trabalho e ajuda a garantir que você esteja protegendo as cargas de trabalho com o nível certo de proteção.

A verificação de dados PII na BlueXP ransomware protection geralmente está disponível para clientes que implantaram a BlueXP classification.  A BlueXP classification está disponível como parte da plataforma BlueXP sem custo adicional e pode ser implantada no local ou na nuvem do cliente.

Para iniciar a verificação, na página Proteção, selecione *Identificar exposição* na coluna Exposição à privacidade do painel de proteção. Para obter mais informações, consulte https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-classify.html["Verifique dados confidenciais identificáveis pessoalmente com BlueXP classification"].



=== Integração do SIEM com o Microsoft Sentinel

Agora você pode enviar dados ao seu sistema de gerenciamento de segurança e eventos (SIEM) para análise e detecção de ameaças usando o Microsoft Sentinel.  Anteriormente, você podia selecionar o AWS Security Hub ou o Splunk Cloud como seu SIEM.

https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-siem.html["Saiba mais sobre como configurar as configurações de BlueXP ransomware protection"].



=== Teste grátis agora por 30 dias

Com este lançamento, novas implantações da BlueXP ransomware protection agora têm 30 dias de teste gratuito.  Anteriormente, a BlueXP ransomware protection oferecia 90 dias de teste gratuito.  Se você já estiver no teste gratuito de 90 dias, a oferta continuará por 90 dias.



=== Restaurar a carga de trabalho do aplicativo no nível de arquivo para Podman

Antes de restaurar uma carga de trabalho de aplicativo no nível de arquivo, agora você pode visualizar uma lista de arquivos que podem ter sido afetados por um ataque e identificar aqueles que deseja restaurar.  Anteriormente, se os Conectores BlueXP em uma organização (anteriormente uma conta) estivessem usando o Podman, esse recurso era desabilitado.  Agora está habilitado para o Podman.  Você pode deixar que a BlueXP ransomware protection escolha os arquivos a serem restaurados, pode enviar um arquivo CSV que lista todos os arquivos afetados por um alerta ou pode identificar manualmente quais arquivos deseja restaurar.

https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-recover.html["Saiba mais sobre como se recuperar de um ataque de ransomware"] .
