= O bloqueio de extensões está habilitado no nível da carga de trabalho.
:allow-uri-read: 




=== O bloqueio de extensões está habilitado no nível da carga de trabalho.

Ao ativar o bloqueio de extensão, ele passa a ser ativado no nível da carga de trabalho, e não no nível da máquina virtual de armazenamento.



=== Editar o status de alerta de comportamento do usuário

O recurso Resiliência a Ransomware agora permite editar o status dos alertas de comportamento do usuário. Você pode descartar e resolver alertas manualmente.

Para mais informações, consulte link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-alert.html["Gerencie alertas em Resiliência a Ransomware"^].



=== Suporte para vários agentes de console

O Ransomware Resilience agora suporta o uso de vários agentes de console para gerenciar os mesmos sistemas.

Para obter mais informações sobre agentes do Console, consultelink:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-start-setup.html["Criar um agente de console"] .
