= Suporte aprimorado para restaurações limpas
:allow-uri-read: 




[[enhanced-support-for-clean-restores]]
=== Suporte aprimorado para restaurações limpas

Agora, restaurações limpas estão disponíveis para recuperação após comportamentos suspeitos do usuário e ataques de criptografia baseados no usuário. Essa melhoria complementa o suporte já existente para ataques baseados em criptografia (entropia). Essa funcionalidade aprimorada permite que você aproveite a abordagem guiada da restauração limpa, identificando os pontos de restauração ideais para minimizar a perda de dados e acelerar a recuperação.

Para obter mais informações, consulte link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-clean-restore.html["Crie um ambiente de recuperação isolado para uma restauração limpa"^].



[[san-support-for-google-cloud-netapp-volumes]]
=== Suporte a SAN para o Google Cloud NetApp Volumes

A NetApp Ransomware Resilience agora oferece suporte a cargas de trabalho SAN do Google Cloud NetApp Volumes, permitindo que você detecte ataques de ransomware baseados em criptografia para cargas de trabalho SAN. O suporte para SAN no Google Cloud NetApp Volumes já está disponível de forma geral.

Para obter mais informações, consulte link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html#supported-systems["sistemas suportados"^] e link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-limitations.html["Armazenamento SAN na resiliência a ransomware"^].
