= Excluir caminhos de arquivos dos alertas de comportamento do usuário
:allow-uri-read: 




[[exclude-file-paths-from-user-behavior-alerts]]
=== Excluir caminhos de arquivos dos alertas de comportamento do usuário

O Ransomware Resilience permite excluir caminhos de arquivo específicos dos alertas de monitoramento de comportamento do usuário. Você pode excluir caminhos de arquivo se souber que eles não estão em risco ou se estiver realizando operações em arquivos em um volume que possam acionar alertas.

Para mais informações, consulte link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-users-manage.html["Excluir caminhos de arquivos dos alertas"^].



[[arm-template-for-microsoft-sentinel]]
=== Modelo ARM para Microsoft Sentinel

O Ransomware Resilience agora oferece um modelo Azure Resource Manager (ARM) para conexão com o Microsoft Sentinel como um SIEM, oferecendo um método secundário para facilitar a implantação.

Para mais informações, consulte link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-siem.html["Conecte-se a um SIEM para detecção e análise de ameaças"^].
