= Padronize grupos de proteção com base na carga de trabalho e no tipo de sistema
:allow-uri-read: 




[[standardize-protection-groups-based-on-workload-and-system-type]]
=== Padronize grupos de proteção com base na carga de trabalho e no tipo de sistema

A Resiliência contra Ransomware agora exige que os grupos de proteção incluam apenas um tipo de carga de trabalho e um tipo de sistema. Ao criar um novo grupo de proteção, você deve designar tanto o tipo de carga de trabalho (sistema de arquivos ou bloco) quanto o sistema para a carga de trabalho. Essa melhoria garante que a estratégia de proteção contra ransomware escolhida para o grupo de proteção possa ser aplicada com sucesso a todas as cargas de trabalho do grupo.

Se você já possui grupos de proteção que combinam tipos de sistema e de carga de trabalho, pode continuar a usá-los, mas não pode adicionar cargas de trabalho ao grupo de proteção.

Para obter mais informações, consulte link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-protection-group.html["Crie um grupo de proteção"^].



[[readiness-drill-enhancement]]
=== Aprimoramento do treinamento de prontidão

O Ransomware Resilience agora permite que você realize simulações de prontidão com base no tipo de ataque. O Ransomware Resilience detecta cinco tipos de ataques, e você pode realizar simulações de prontidão para cada um deles para simular o ataque e o processo de recuperação e entender sua prontidão para um ataque de ransomware.

Para obter mais informações, consulte link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-start-simulate.html["Realize um exercício de prontidão"^].



[[pause-or-delete-a-siem-system]]
=== Pausar ou excluir um sistema SIEM

A Resiliência contra Ransomware agora inclui opções na interface do usuário para pausar ou excluir um sistema SIEM. Essa melhoria facilita a desativação temporária do sistema para solução de problemas ou manutenção ou sua remoção completa.

Para obter mais informações, consulte link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-siem.html#disable-a-siem-system["Desativar um sistema SIEM"^].
